openapi: 3.0.0
info:
  title: Todo Backend API
  version: 1.0.0
  description: API for managing tasks in a multi-user Todo application

servers:
  - url: http://localhost:8000/api/v1
    description: Development server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Verify API availability
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    example: "2023-10-27T10:00:00Z"

  /tasks:
    get:
      summary: List tasks for authenticated user
      description: Retrieve all tasks belonging to the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: completed
          in: query
          required: false
          schema:
            type: boolean
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      summary: Create a new task
      description: Create a new task for the authenticated user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task owned by the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
    put:
      summary: Update a specific task
      description: Update a specific task owned by the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
    delete:
      summary: Delete a specific task
      description: Delete a specific task owned by the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

  /tasks/{task_id}/toggle:
    patch:
      summary: Toggle task completion status
      description: Toggle the completion status of a specific task owned by the authenticated user
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique identifier for the task
          example: 1
        user_id:
          type: string
          description: ID of the user who owns the task
          example: "user_12345"
        title:
          type: string
          description: Title of the task
          minLength: 1
          maxLength: 200
          example: "Complete project proposal"
        description:
          type: string
          description: Optional description of the task
          maxLength: 1000
          example: "Finish the project proposal document and submit for review"
        completed:
          type: boolean
          description: Whether the task is completed
          example: false
        created_at:
          type: string
          format: date-time
          description: Timestamp when the task was created
          example: "2023-10-27T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the task was last updated
          example: "2023-10-27T10:00:00Z"
        due_date:
          type: string
          format: date-time
          description: Optional due date for the task
          example: "2023-10-30T10:00:00Z"

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          description: Title of the task
          minLength: 1
          maxLength: 200
          example: "Complete project proposal"
        description:
          type: string
          description: Optional description of the task
          maxLength: 1000
          example: "Finish the project proposal document and submit for review"
        completed:
          type: boolean
          description: Whether the task is completed
          default: false
        due_date:
          type: string
          format: date-time
          description: Optional due date for the task
          example: "2023-10-30T10:00:00Z"

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          description: Updated title of the task
          minLength: 1
          maxLength: 200
          example: "Complete project proposal"
        description:
          type: string
          description: Updated description of the task
          maxLength: 1000
          example: "Finish the project proposal document and submit for review"
        completed:
          type: boolean
          description: Updated completion status of the task
          example: true
        due_date:
          type: string
          format: date-time
          description: Updated due date for the task
          example: "2023-10-30T10:00:00Z"

    ErrorResponse:
      type: object
      required:
        - detail
        - error_code
        - timestamp
        - request_id
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: "Invalid or expired authentication token"
        error_code:
          type: string
          description: Machine-readable error code
          example: "INVALID_CREDENTIALS"
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 formatted timestamp
          example: "2023-10-27T10:00:00Z"
        request_id:
          type: string
          description: Unique identifier for the request
          example: "req_abc123"

  responses:
    UnauthorizedError:
      description: Invalid or missing authentication token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    BadRequestError:
      description: Invalid request parameters or body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFoundError:
      description: Requested resource does not exist
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'